services:
  hashflow.api:
    build:
      context: .
      dockerfile: HashFlow/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    
    environment:
      ACCEPT_EULA : "Y"
      SA_PASSWORD: "Pa55wordHello"
  
  hashProcessor:
    build:
      context: .
      dockerfile: HashProcessor/Dockerfile
    
  rabbitMQ:
    image: "rabbitmq:3.10.7-management"
    hostname: "rabbitmq"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=hashesAdmin
      - RABBITMQ_DEFAULT_PASS=hashesPassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - "5672:5672"
      - "15672:15672"